version: '3.8'

services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
    command:
      [
        'wait-for-it/wait-for-it.sh',
        'postgres://user:password@db:5432/music',
        '--timeout=1',
        '--',
        'npm',
        'run',
        'migrate-and-start',
      ]
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: music

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
